# Generated by Django 5.0.6 on 2024-08-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='villas',
            name='rooms',
            field=models.IntegerField(default='2'),
            preserve_default=False,
        ),
    ]
