# Generated by Django 5.0.6 on 2024-08-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_villas_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='villas',
            name='location',
            field=models.CharField(default='22', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='villas',
            name='status',
            field=models.CharField(default='jerico', max_length=20),
            preserve_default=False,
        ),
    ]
