# Generated by Django 5.0.6 on 2024-08-26 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_villas_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited_by', to='group.villas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='group.user')),
            ],
        ),
    ]
