# Generated by Django 5.0.6 on 2024-08-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_favoritevilla_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='FavoriteVilla',
        ),
    ]
