# Generated by Django 5.0.6 on 2024-08-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_followup_delete_favoritevilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction', models.IntegerField()),
                ('recommendation', models.IntegerField()),
                ('ease_of_use', models.IntegerField()),
            ],
        ),
    ]
